// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBbO7Cl1lnAEAund-9vD3hZOTUrFOclJvA',
    appId: '1:792821712092:web:73574d234584332f3f2019',
    messagingSenderId: '792821712092',
    projectId: 'practicefirebase-ebeee',
    authDomain: 'practicefirebase-ebeee.firebaseapp.com',
    storageBucket: 'practicefirebase-ebeee.appspot.com',
    measurementId: 'G-5KC1Z2758R',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDKAvM6ZkjbqLDd_S8Iurcq5yuNVXP84jY',
    appId: '1:792821712092:android:ae159065ddac656c3f2019',
    messagingSenderId: '792821712092',
    projectId: 'practicefirebase-ebeee',
    storageBucket: 'practicefirebase-ebeee.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCrwAFh34wfzJSqRI-jzdf8CQQimRLzBRM',
    appId: '1:792821712092:ios:cc88afa3f7a8e8a43f2019',
    messagingSenderId: '792821712092',
    projectId: 'practicefirebase-ebeee',
    storageBucket: 'practicefirebase-ebeee.appspot.com',
    iosClientId: '792821712092-ac040pv27qcs7hjvau049jgd975rmgnb.apps.googleusercontent.com',
    iosBundleId: 'com.example.practiceFirebase',
  );
}
